Reddit/config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:new, :create, :show] do
    resources :subs, only: [:new, :create, :update, :edit, :destroy ]
  end

  resources :subs, only: [:show, :index]

  resource :session, only: [:new, :create, :destroy]
end

Reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  user_id     :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Sub < ApplicationRecord
  validates :title, presence: true

  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User,
    inverse_of: :subs
end

Reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    before_validation :ensure_session_token

    validates :username, :session_token, uniqueness: true
    validates :username, :password_digest, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }

    has_many :subs,
        foreign_key: :user_id,
        class_name: :Sub,
        dependent: :destroy,
        inverse_of: :moderator

    attr_reader :password

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        user && user.is_valid_password?(password) ? user : nil
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_valid_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user,:logged_in?
    
    #hcrlll
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logout!
        current_user.reset_session_token! 
        session[:session_token] = nil
        @current_user = nil
    end

    def logged_in?
        !!current_user
    end
end

Reddit/app/controllers/session_controller.rb
class SessionController < ApplicationController

  before_action :require_logged_in, only: [:destroy]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_logged_in, only: [:destroy]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new(username: params[:user][:username])
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in,except:[:show,:index]
  
  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = params[:user_id]
    if @sub.save 
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update  
    @sub = Sub.find_by(id: params[:id])
    if @sub.update(sub_params)
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render sub_url(@sub)
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    if @sub && sub.moderator == current_user.id
      @sub.destroy
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render sub_url(@sub)
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description,:user_id)
  end

end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only:[:show]

  def new
    @user = User.new 
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:username,:password)
  end

end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

Reddit/app/helpers/session_helper.rb
module SessionHelper
end

Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit/app/helpers/users_helper.rb
module UsersHelper
end

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Reddit/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

Reddit/app/views/subs/index.html.erb
<h1>All Subs</h1>

<% @subs.each do |sub| %>
    <li>

        <a href="<%= sub_url(sub) %>">
            <%= sub.title %>
        </a>

    </li>
<% end %>

Reddit/app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

Reddit/app/views/subs/show.html.erb
<h1><%=User.find_by(id: @sub.user_id).username%>'s Sub</h1>
    <label>Title:
        <%= @sub.title%>
    </label>
    <br>
    <label>Description:
        <%= @sub.description%>
    </label>
    <br>
    <label>Moderator:
        <%=User.find_by(id: @sub.user_id).username%>
    </label>

Reddit/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Username
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>
    <label>Password
        <input type="password" name="user[password]" value="<%= @user.password %>">
    </label>
    <button type="submit">Sign Up</button>
</form>

Reddit/app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>

<% @user.subs.each do |sub| %>
    <li>

        <a href="<%= sub_url(sub) %>">
            <%= sub.title %>
        </a>

    </li>
<% end %>